version: '3.6'


volumes:
  redis:

services:

  redis:
    restart: always
    hostname: redis
    image: redis:latest
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - redis:/data

  nginx:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NGINX_VERSION: 1.18.0
    image: nginx-srcache:1.18.0
    ports:
      - "127.0.0.1:8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - "./www:/usr/share/nginx/html"
    depends_on:
      - redis
    #entrypoint: sleep 99999
